# Generated by Django 3.0.7 on 2020-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
