# Generated by Django 3.0.7 on 2020-06-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200616_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
